### ISSUE TITLE
Trying to understand more about supported instruction set?

### ISSUE THREAD

**Issue by jkingsman** [MohammedRashad/ArduZ80#4]
Hi there! 

I'm building a sort of Z80 emulator on Arduino and was thrilled to find your library.

I'm trying to understand a bit more about the instruction set supported by ArduZ80. As an example, `3E XX` should be `LD A, $XX` ([ref](https://clrhome.org/table/)) but instead is an unsupported opcode. I tried digging into the enum in the header file and things seemed a little haphazard in terms of opcode support. 

Was there a particular pattern to the opcodes you chose to support? 

Thanks for any help you can offer!

**Comment by jkingsman** [comment]
I ended up writing my own wrapper lib around a fully complete z80 core -- https://github.com/jkingsman/Z80Mega

**Comment by MohammedRashad** [comment]
Truly amazing, I wrote the project years ago when I was still learning the z80, so probably I followed inaccuracte opcode pattern or at least the simulator I built upon wasn't accurate to the datasheet. 

I really appreaciate your efforts to push the idea further.
